#!/bin/bash





curl -iXPOST "https://csye6225-fall2018-chengl.me:8080/csye6225Webapp-1.0-SNAPSHOT/transaction/49/attachment" -H "username:leoleoleocheng@gmail.com" -H "password:leo38377" -F receipt=@"newReceipt.jpg"
